version: "3.5"

services:
  cineflex-db:
    container_name: cineflex-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    # volumes:
    #   - /usr/local/db/data:/var/lib/post/data